<div class="row fays-four-links">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="fays-block">
            <a href="<?= $this->link1 ?>">
                <?= $this->link1Text ?>
            </a>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="fays-block">
            <a href="<?= $this->link2 ?>">
                <?= $this->link2Text ?>
            </a>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="fays-block">
            <a href="<?= $this->link3 ?>">
                <?= $this->link3Text ?>
            </a>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="fays-block">
            <a href="<?= $this->link4 ?>">
                <?= $this->link4Text ?>
            </a>
        </div>
    </div>
</div>
